<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_WaterValue</name>
   <tag></tag>
   <elementGuidId>a533e0d4-f9ba-41fd-bbc5-359627644409</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*[@id='LimitedWaterBackupLimitBlock']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='LimitedWaterBackupLimitBlock']</value>
   </webElementProperties>
</WebElementEntity>
